import Foundation

@main
struct StateStoreManualMain {
    static func main() throws {
        do {
            try testAppPathsLivePrefersICUAppSupportRootOverride()
            try testRuntimeLaunchDiagnosticsIncludeBundleAndAppSupportPaths()
            try testRuntimeLaunchDiagnosticsUsesRepoModeWhenRepoRootIsOutsideBundleResources()
            try testRuntimeLaunchDiagnosticsEmitWritesImmediatelyToProvidedOutput()
            try testTextCatalogReturnsBaseValueWhenNoOverrideExists()
            try testTextCatalogUsesOverrideWithoutDroppingBaseFallback()
            try testTextCatalogFallsBackToCallerDefaultForUnknownKey()
            try testBaseCopyCatalogContainsAllSourceReferencedKeys()
            try testDesktopPetCopyUsesInstalledCatalogForSessionMessages()
            try testUserFacingErrorCopyUsesInstalledCatalogForWorkSessionErrors()
            try testUserFacingErrorCopyUsesInstalledCatalogForAvatarBridgeErrors()
            try testStateStoreCreatesICUDirectoriesAndDefaultsToIdle()
            try testAllowsIdleWorkingFocusWorkingBreakWorkingIdleFlow()
            try testRejectsBreakToFocusShortcut()
            try testPersistWindowPlacementUpdatesCurrentStateAndStore()
            try testStateTransitionsPreserveSavedWindowPlacement()
            try testLaunchResetsPersistedActiveSessionToIdleWhilePreservingWindowPlacement()
            try testIdleMenuShowsStartWork()
            try testIdleMenuShowsGenerationConfigEntryInUtilitySection()
            try testWorkingMenuSectionsStayGroupedForThemedPanel()
            try testStatusItemMenuExposesGenerationConfig()
            try testMenuActionTitlesCanBeOverriddenByTextCatalog()
            try testWorkingMenuShowsFocusAndBreakActions()
            try testPausedStatesShowResumeAction()
            try testWorkingStateArmsEyeReminder()
            try testFocusSuspendsEyeReminder()
            try testResumeWorkingRearmsEyeReminder()
            try testHealthMetricsStorePersistsReminderEventsAndIgnoresDuplicateOutcomes()
            try testHealthMetricsStoreBuildsWeekSummaryFromMultipleDays()
            try testHealthMetricsStoreRecoversFromCorruptMetricsFileAndRecordsDiagnostic()
            try testHealthMetricsStoreEmitsDiagnosticsForIgnoredInvalidEvents()
            try testHealthMetricsStoreSerializesConcurrentWrites()
            try testHealthSessionTrackerSettlesWorkFocusAndBreakMetricsAcrossTransitions()
            try testHealthSessionTrackerOnlyRequestsStopWorkReportWhenDataExists()
            try testAvatarCatalogListsRepoAvatar()
            try testAvatarCatalogPrefersAppAssetsOverRepoAvatar()
            try testAvatarAssetStoreUsesInstalledCopyCatalogForGeneratedStyleLabel()
            try testAvatarAssetStoreWritesCustomAvatarFiles()
            try testAvatarSettingsStorePersistsCurrentAvatarID()
            try testAvatarSettingsStoreFallsBackToNilWhenSettingsFileIsMissing()
            try testAvatarSettingsStorePersistsImageModelsWithoutLosingAvatarSettings()
            try testAvatarSettingsStoreFallsBackToRepoSettingsAndWritesUserSelectionToAppSupport()
            try testAvatarBuilderBridgeParsesOptimizePromptJSON()
            try testAvatarBuilderBridgeSurfacesBridgeFailure()
            try testAvatarBuilderBridgeErrorPrefixCanBeOverriddenByTextCatalog()
            try testPetAssetLocatorFallsBackToRepoBaseImage()
            try testPetAssetLocatorAcceptsBundledRuntimeRootWithoutSwiftPackage()
            try testPetAssetLocatorPrefersAppSupportAssetOverRepoAsset()
            try testPetAssetLocatorPrefersActionFrameBeforeBase()
            try testPetAssetLocatorResolvesMultiFrameDirectoryAnimation()
            try testPetAssetLocatorNormalizesLegacySingleFrameAnimation()
            try testPetAssetLocatorAppliesConfigAnimationOverrides()
            try testPetAssetLocatorDoesNotDuplicateMainVariantWhenItIsDefault()
            try testPetAssetLocatorFallsBackAnimationStateOrderThenBaseImage()
            try testDefaultOriginUsesVisibleFrameBottomRight()
            try testResolveInitialOriginPrefersSavedVisiblePosition()
            try testResolveInitialOriginFallsBackWhenSavedPositionIsOutOfBounds()
            try testGenerationSettingsStorePersistsCapabilitiesWithoutDroppingAvatarState()
            try testGenerationSettingsStoreFallsBackToRepoSettingsAndMigratesWritesToAppSupport()
            try testGenerationSettingsStoreIgnoresBooleanOptionsWhenLoading()
            try testThemeManagerFallsBackToPixelThemeWhenStoredPackIsInvalid()
            try testThemeManagerApplyPersistsPackAndLoadsOnNextStartup()
            try testThemeGenerationServiceCanGenerateDraftWithoutApplying()
            try testThemeGenerationServiceUsesTextThenCodeCapabilities()
            try testGenerationCapabilityRouterReturnsAnimationAvatarCapability()
            try testGenerationCapabilityRouterRejectsUnsupportedTextDescriptionProvider()
            try testThemeGenerationServiceKeepsCurrentThemeWhenGeneratedPackIsInvalid()
            try testThemeGenerationServiceRejectsEmptyVibeBeforeNetworkCall()
            try testThemeGenerationServiceThrowsRecoverableErrorForMissingCapabilityConfig()
            try testSpeechGenerationServiceUsesTextCapabilityAndReturnsDraft()
            try testSpeechGenerationServiceRejectsUnsupportedTextProviderBeforeNetworkCall()
            try testCopyOverrideStoreAppliesSpeechDraftAndPreservesUnrelatedOverrides()
            try testGenerationRouteErrorEmptyVibeUsesCopyCatalogMessage()
            print("StateStoreManualTests: PASS")
        } catch {
            fputs("StateStoreManualTests: FAIL - \(error)\n", stderr)
            exit(1)
        }
    }
}
